name: agglomerative_clustering_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.4
  - pandas=1.5.3
  - matplotlib=3.8.0
  - scipy=1.11.3
  - plotly=5.17.0
  - scikit-learn=1.3.1
  - pip=23.2.1
  - pip:
    - wandb==0.15.12
