name: visualization_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.4
  - pandas=1.5.3
  - seaborn=0.13.0
  - matplotlib=3.8.0
  - numpy=1.24.3
  - plotly=5.17.0
  - pip=23.2.1
  - pip:
    - wandb==0.15.12
