name: devops_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.4
  - pandas=1.5.3
  - scikit-learn=1.3.0
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - jupyter=1.0.0
  - pip:
    - mlflow=1.20.2
    - scipy=1.10.1
    - numpy=1.24.3
    - plotly=5.9.0
    - logging=0.5.1.2
    - os=0.1.1
    - sys=0.3.4
    - datetime=4.3
    - rand=0.4.6
    - scikit-learn=1.0
