name: devops_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.4
  - pandas=1.5.3
  - scikit-learn=1.3.0
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - jupyter=1.0.0
  - pytest=7.4.0
  - mlflow=1.20.2
  - scipy=1.10.1
  - numpy=1.24.3
  - pip=23.2.1
  - pip:
    - plotly==5.9.0
    - wandb==0.12.4
    - pyyaml==6.0
    - mlflow==1.20.2
    - pytest==7.4.0
    - hydra-core==1.1.1
