name: descriptive_stats_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.4
  - pandas=1.5.3
  - seaborn=0.13.0
  - matplotlib=3.8.0
  - pip=23.2.1
  - pip:
    - wandb==0.15.12
    - mlflow==2.9.1