wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.12
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1702205227.255885
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 13
      - 23
      - 24
      4: 3.11.4
      5: 0.15.12
      8:
      - 3
      - 5
      13: windows-amd64
_items:
  desc: null
  value:
    _wandb: {}
_locked:
  desc: null
  value: {}
_users:
  desc: null
  value: {}
_users_inv:
  desc: null
  value: {}
_users_cnt:
  desc: null
  value: 0
_callback:
  desc: null
  value: wandb.sdk.wandb_run.Run._config_callback
_settings:
  desc: null
  value:
    _args: []
    _aws_lambda: false
    _async_upload_concurrency_limit: null
    _cli_only_mode: null
    _colab: false
    _cuda: null
    _disable_meta: false
    _disable_service: false
    _disable_setproctitle: false
    _disable_stats: false
    _disable_viewer: null
    _disable_machine_info: false
    _except_exit: true
    _executable: C:\Users\39339\anaconda3\envs\devops_env\python.exe
    _extra_http_headers: null
    _file_stream_retry_max: 125
    _file_stream_retry_wait_min_seconds: 2
    _file_stream_retry_wait_max_seconds: 60
    _file_stream_timeout_seconds: 180
    _file_uploader_retry_max: 10
    _file_uploader_retry_wait_min_seconds: 2
    _file_uploader_retry_wait_max_seconds: 60
    _file_uploader_timeout_seconds: 0
    _flow_control_custom: false
    _flow_control_disabled: false
    _graphql_retry_max: 10
    _graphql_retry_wait_min_seconds: 2
    _graphql_retry_wait_max_seconds: 60
    _graphql_timeout_seconds: 30
    _internal_check_process: 8.0
    _internal_queue_timeout: 2.0
    _ipython: false
    _jupyter: false
    _jupyter_name: null
    _jupyter_path: null
    _jupyter_root: null
    _kaggle: false
    _live_policy_rate_limit: null
    _live_policy_wait_time: null
    _log_level: 10
    _network_buffer: null
    _noop: false
    _notebook: false
    _offline: false
    _sync: false
    _os: Windows-10-10.0.19045-SP0
    _platform: windows
    _proxies: null
    _python: 3.11.4
    _runqueue_item_id: null
    _require_nexus: false
    _save_requirements: true
    _service_transport: null
    _service_wait: 30.0
    _start_datetime: '20231210_114707'
    _start_time: 1702205227.2397025
    _stats_pid: 29080
    _stats_sample_rate_seconds: 2.0
    _stats_samples_to_average: 15
    _stats_join_assets: true
    _stats_neuron_monitor_config_path: null
    _stats_open_metrics_endpoints: null
    _stats_open_metrics_filters:
    - .*
    _stats_disk_paths:
    - /
    _stats_buffer_size: 0
    _tmp_code_dir: C:\Users\39339\Documents\University materials\University materials\Erasmus
      IE\DevOps\Devops_Project\wandb\run-20231210_114707-mp8dxfhb\tmp\code
    _tracelog: null
    _unsaved_keys: null
    _windows: true
    allow_val_change: null
    anonymous: null
    api_key: null
    azure_account_url_to_access_key: null
    base_url: https://api.wandb.ai
    code_dir: null
    colab_url: null
    config_paths: null
    console: wrap
    deployment: cloud
    disable_code: false
    disable_git: false
    disable_hints: null
    disable_job_creation: false
    disabled: false
    docker: null
    email: mcaru.exstudents2023@student.ie.edu
    entity: devops_project
    files_dir: C:\Users\39339\Documents\University materials\University materials\Erasmus
      IE\DevOps\Devops_Project\wandb\run-20231210_114707-mp8dxfhb\files
    force: null
    git_commit: 30521852f09ff24b602e37f459893915360d574c
    git_remote: origin
    git_remote_url: https://github.com/Matcar02/Devops_Project_Customer_Segmentation.git
    git_root: null
    heartbeat_seconds: 30
    host: DESKTOP-4HMEBO5
    ignore_globs: []
    init_timeout: 90.0
    is_local: false
    job_name: null
    job_source: null
    label_disable: null
    launch: null
    launch_config_path: null
    log_dir: C:\Users\39339\Documents\University materials\University materials\Erasmus
      IE\DevOps\Devops_Project\wandb\run-20231210_114707-mp8dxfhb\logs
    log_internal: C:\Users\39339\Documents\University materials\University materials\Erasmus
      IE\DevOps\Devops_Project\wandb\run-20231210_114707-mp8dxfhb\logs\debug-internal.log
    log_symlink_internal: C:\Users\39339\Documents\University materials\University
      materials\Erasmus IE\DevOps\Devops_Project\wandb\debug-internal.log
    log_symlink_user: C:\Users\39339\Documents\University materials\University materials\Erasmus
      IE\DevOps\Devops_Project\wandb\debug.log
    log_user: C:\Users\39339\Documents\University materials\University materials\Erasmus
      IE\DevOps\Devops_Project\wandb\run-20231210_114707-mp8dxfhb\logs\debug.log
    login_timeout: null
    mode: online
    notebook_name: null
    problem: fatal
    program: C:\Users\39339\anaconda3\envs\devops_env\Scripts\pytest-script.py
    program_abspath: C:\Users\39339\anaconda3\envs\devops_env\Scripts\pytest-script.py
    program_relpath: ..\..\..\..\..\..\anaconda3\envs\devops_env\Scripts\pytest-script.py
    project: Customer_Segmentation
    project_url: https://wandb.ai/devops_project/Customer_Segmentation
    quiet: null
    reinit: null
    relogin: null
    resume: null
    resume_fname: C:\Users\39339\Documents\University materials\University materials\Erasmus
      IE\DevOps\Devops_Project\wandb\wandb-resume.json
    resumed: false
    root_dir: C:\Users\39339\Documents\University materials\University materials\Erasmus
      IE\DevOps\Devops_Project
    run_group: null
    run_id: mp8dxfhb
    run_job_type: null
    run_mode: run
    run_name: Kmeans_Experiment
    run_notes: null
    run_tags: null
    run_url: https://wandb.ai/devops_project/Customer_Segmentation/runs/mp8dxfhb
    sagemaker_disable: null
    save_code: null
    settings_system: C:\Users\39339\.config\wandb\settings
    settings_workspace: C:\Users\39339\Documents\University materials\University materials\Erasmus
      IE\DevOps\Devops_Project\wandb\settings
    show_colors: null
    show_emoji: null
    show_errors: true
    show_info: true
    show_warnings: true
    silent: false
    start_method: null
    strict: null
    summary_errors: null
    summary_timeout: 60
    summary_warnings: 5
    sweep_id: null
    sweep_param_path: null
    sweep_url: ''
    symlink: false
    sync_dir: C:\Users\39339\Documents\University materials\University materials\Erasmus
      IE\DevOps\Devops_Project\wandb\run-20231210_114707-mp8dxfhb
    sync_file: C:\Users\39339\Documents\University materials\University materials\Erasmus
      IE\DevOps\Devops_Project\wandb\run-20231210_114707-mp8dxfhb\run-mp8dxfhb.wandb
    sync_symlink_latest: C:\Users\39339\Documents\University materials\University
      materials\Erasmus IE\DevOps\Devops_Project\wandb\latest-run
    system_sample: 15
    system_sample_seconds: 2
    table_raise_on_max_row_limit_exceeded: false
    timespec: '20231210_114707'
    tmp_dir: C:\Users\39339\Documents\University materials\University materials\Erasmus
      IE\DevOps\Devops_Project\wandb\run-20231210_114707-mp8dxfhb\tmp
    username: '39339'
    wandb_dir: C:\Users\39339\Documents\University materials\University materials\Erasmus
      IE\DevOps\Devops_Project\wandb\
_artifact_callback:
  desc: null
  value: wandb.sdk.wandb_run.Run._config_artifact_callback
